<?php

/**
 * Created by PhpStorm.
 * User: dhirajpatra
 * Date: 22/3/17
 * Time: 9:51 PM
 */

/**
 * Class streamSampler
 * stream-sampler that receives and processes an input stream consisting of
 * single characters.
 * The stream is of unknown and possibly very large length and the program should work regardless
 * of the size of the input.
 * The program should take the sample size as a parameter and generate a random representative
 * sample using that many characters.
 * As for receiving the data the tool should work with two kinds of inputs:
 * values piped directly into the process using
 * cat input.txt | stream-sampler 5
 * values generated by using a random source from within the language
 */
class StreamSampler
{
    /**
     * this method will process the string and generate a randon word size as per parameter
     * @param global $argc
     * @param global $argv
     */
    public static function makeSample()
    {
        try {
            // argc and argv need/take to declare as global
            global $argc, $argv;
            $length = $argv[1]; // length of the random word

            $result = '';
            if ($argc > 1) {
                $inputString = null;

                // Read from the stream of character from pipe
                $fp = fopen("php://stdin", "r");
                $read  = array($fp);
                $write = null;
                $except = null;

                // check whether file inputed or not
                if (stream_select($read, $write, $except, 0) === 1) {
                    // creating char array from stream
                    $inputString = str_split(stream_get_contents($fp));
                    fclose($fp);
                }

                if ($inputString != null) {
                    // get random postion from char array
                    $positions = array_rand($inputString, $length);
                    foreach ($positions as $position) {
                        $result .= $inputString[$position];
                    }
                } else {
                    // take random string of characters
                    $result = substr(str_shuffle(implode(array_merge(range('A', 'Z'), range('a', 'z')))), 0, $length);
                }
            } else {
                echo 'Please enter all parameters';
                exit();
            }
            // display the result
            return strtoupper($result);
        } catch (Exception $e) {
            echo 'Something wrong ' . $e->getMessage();
        }
    }
}
